'use client';

import { useState } from 'react';
import { SiteFooter, SiteHeader } from '../../../components/site-shell';
import { Detail, Reveal, SectionHeading, Segmented, Waveform } from '../../../components/ui';

const manualTasks = ['Prepare cameras', 'Capture cards', 'Set up OBS', 'Check signal', 'Start recording', 'Record audio', 'Watch OBS', 'Notice a black frame', 'Notice a frozen feed', 'Switch cameras', 'Track timing', 'Stop recording', 'Find files', 'Whose set is this?', 'Synchronize cameras', 'Synchronize master', 'Cut sets', 'Process audio', 'Render', 'Check the render', 'Upload', 'Find the contact', 'Send delivery', 'Who is still waiting?', 'Keep the archive tidy', 'Find an old project'];
const levels = [
  ['Reliable', 'Reliability comes first.', 'Recording automation · health checks · fallbacks · OBS control · manual override · event logging', 'Recording continues, faults are noticed, and people keep control.'],
  ['Aware', 'The system understands context.', 'Audio analysis · camera analysis · artist timeline · automatic synchronization · archive integration', 'Signals, artists, and files belong to one event and one timeline.'],
  ['Director', 'Directing appears.', 'Rule-based directing · music-aware cuts · camera quality scoring', 'Editing rules and musical transitions guide the next shot.'],
  ['BRUKXT style', 'Then comes our own voice.', 'Historical edit analysis · BRUKXT Editing Grammar · supervised dataset · learned Director', 'Training rests on checked data and reliable infrastructure.'],
];

function SignalDiagram() {
  return <div className="signal-diagram" aria-label="Cameras, audio, and a timeline combine into Media Engine and a finished set"><div className="signal-inputs">{['CAM A', 'CAM B', 'CAM C', 'MASTER', 'TIMELINE'].map((name, index) => <div key={name}><span>{name}</span>{index < 4 ? <Waveform seed={index} /> : <div className="mini-timeline"><i /><i /><i /></div>}</div>)}</div><svg className="signal-wires" viewBox="0 0 230 240" preserveAspectRatio="none" aria-hidden="true">{[24, 72, 120, 168, 216].map((y, index) => <path key={y} pathLength="100" className={`wire wire-${index}`} d={`M 0 ${y} H 50 C 125 ${y} 100 120 180 120 H 230`} />)}</svg><div className="signal-engine"><span className="micro">CLUBOS / MEDIA</span><span className="engine-mark" aria-hidden="true"><i /><i /><i /></span><strong>Fewer actions.<br />More control.</strong></div><div className="signal-output"><span className="output-line" /><div><span className="ready-dot">✓</span><strong>SET READY</strong><span className="micro">ARTIST → ARCHIVE</span></div></div></div>;
}

export default function EnglishMediaPage() {
  const [workflow, setWorkflow] = useState(0);
  const [level, setLevel] = useState(0);
  return <><a className="skip-link" href="#main">Skip to content</a><SiteHeader current="media" locale="en" /><main id="main"><section className="hero wrap"><div className="hero-meta"><span className="eyebrow">BRUKXT MEDIA ENGINE</span><span className="micro">VISION / PROTOTYPE 01</span></div><h1>The set is over.<br /><span>The work is too.</span></h1><div className="hero-bottom"><p>From the first frame to a finished recording for the artist.<br />Without someone having to remember every step.</p><a href="#burden" className="round-link"><span>See how</span><b aria-hidden="true">↓</b></a></div><SignalDiagram /><div className="hero-caption"><span>MACHINES MONITOR MACHINES.<br className="mobile-only" /> PEOPLE STEER THE SYSTEM.</span><span>A CLUBOS CONCEPT</span></div></section>
    <section className="section light-section" id="burden"><div className="wrap"><Reveal><SectionHeading number="01" label="A FAMILIAR SITUATION" title={<>No action is difficult.<br /><span className="muted">Remembering all of them is.</span></>}>For years, we have done more than film sets. We have followed every file from camera to artist delivery.</SectionHeading></Reveal><div className="workflow-switch"><span className="micro">ONE SET. THE WHOLE PATH.</span><Segmented label="Manual or automated workflow" options={['How it is now', 'How it could be']} value={workflow} onChange={setWorkflow} /></div><div className={`workflow ${workflow ? 'simplified' : ''}`}><div className="task-cloud" aria-hidden={workflow === 1}>{manualTasks.map((task, index) => <span key={task} style={{ '--order': index } as React.CSSProperties}>{task}<small>{String(index + 1).padStart(2, '0')}</small></span>)}</div><div className="simple-flow" aria-hidden={workflow === 0}><div><span className="micro">01 / TRIGGER</span><h3>The artist starts</h3><p>The timeline already has context.</p></div><span className="flow-arrow">→</span><div className="flow-engine"><span className="micro">02 / SYSTEM</span><h3>Media Engine</h3><p>Records. Checks. Prepares.</p></div><span className="flow-arrow">→</span><div><span className="micro">03 / RESULT</span><h3>The artist receives the set</h3><p>The archive is updated.</p></div></div></div><div className="burden-consequences"><div><span>01</span><h3>The recording exists.<br />The result does not.</h3><p>Files pile up, editing becomes a queue, and artists wait.</p></div><div><span>02</span><h3>A fault happened.<br />We do not know yet.</h3><p>A black frame, frozen card, or missing master feed may appear only after the set.</p></div><div><span>03</span><h3>Everything lives<br />in someone’s memory.</h3><p>Where is the file? Who is still waiting? Who was meant to send it?</p></div></div></div></section>
    <section className="statement wrap"><Reveal><span className="eyebrow">WHAT WE WANT TO GIVE BACK</span><h2>Your attention.</h2><p>To cameras. The room. The music.<br /><span className="muted">Everything we do this for.</span></p></Reveal><div className="statement-note">Not to replace the video team.<br />To lift constant machine supervision from it.</div></section>
    <section className="section control-section"><div className="wrap"><Reveal><SectionHeading number="02" label="THE SYSTEM WORKS. YOU STEER." title={<>Automation.<br /><span className="muted">With your final word.</span></>}>The system prepares, records, and watches the signals. You set the rules, see why decisions were made, and can take over at any time.</SectionHeading></Reveal><div className="test-bench"><div className="bench-hardware"><span className="micro">TEST BENCH / HARDWARE</span><div className="bench-drawing" aria-hidden="true"><div className="draw-cameras"><span>CAM 01</span><span>CAM 02</span></div><div className="draw-capture"><i />2 × HDMI → USB<i /></div><div className="draw-laptop"><span>OBS</span><small>MEDIA ENGINE</small></div><div className="draw-audio">MASTER AUDIO →</div></div><p>2 cameras · 2 capture cards<br />1 laptop · OBS · master audio</p></div><div className="bench-checklist"><span className="micro">MVP / READY CRITERIA</span>{['See both cameras', 'Monitor signal health', 'Start / stop OBS recording', 'Start / stop RAW recording', 'Switch scenes automatically', 'Notice a black or frozen frame', 'Remove a failed source', 'Move safely to a fallback', 'Attempt recovery', 'Log each decision', 'Return control to a person immediately', 'Call for help when needed'].map((text, index) => <div key={text}><span>{String(index + 1).padStart(2, '0')}</span>{text}</div>)}</div></div><div className="bench-software"><span>SOFTWARE</span><p>Media Engine · OBS connector · camera health analysis · Director · Evaluator · Recovery Handler · event log · human control panel</p></div><Detail title="Real time: no large language model between a camera and OBS"><p>Real time relies on inexpensive local computation: camera and audio features, telemetry, state, decisions, rules, and OBS control. Heavier AI can work asynchronously or offline. If an external service is unavailable, local recording, rules, and manual control continue.</p></Detail></div></section>
    <section className="section dark-section"><div className="wrap"><Reveal><SectionHeading number="03" label="NOTHING SHOULD BE LEFT TO MEMORY" title={<>One set.<br /><span className="muted">One continuous path.</span></>}>ClubOS already knows who plays, where, and when. Media Engine knows what to do with signals, files, and the completed result.</SectionHeading></Reveal><div className="pipeline"><div className="panel-heading"><span>FROM EVENT TO ARCHIVE</span></div><div className="pipeline-nodes">{['Event timeline', 'Pre-flight', 'Capture', 'Live Director', 'Health Monitor', 'Raw storage', 'Sync', 'Auto edit', 'Audio master', 'Render', 'QC', 'Upload', 'Artist delivery', 'Archive'].map((name, index) => <div className="pipeline-node" key={name}><span>{String(index + 1).padStart(2, '0')}</span><strong>{name}</strong><span>↗</span></div>)}</div><div className="pipeline-description"><span className="large-index">∞</span><div><h3>Every result stays connected.</h3><p>Event → artist → sources → project → master → delivery. Original files stay intact; uncertain results wait for a person.</p></div></div></div><div className="after-heading"><span className="eyebrow">03:00:00 / ARTIST SET END</span><h2>You close the night.<br /><span className="muted">The system closes the work.</span></h2></div><div className="no-queue"><span>↗</span><p>No forgotten queue of artists.</p></div><Detail title="Audio: the source is immutable, the master is reproducible"><div className="audio-panel"><div className="panel-heading"><span>AUDIO / NON-DESTRUCTIVE</span></div><div className="audio-wave"><Waveform seed={5} /></div><div className="audio-chain">{['Master input', 'RAW WAV', 'Analysis', 'Gain', 'EQ*', 'Compression', 'Limiter', 'Loudness', 'Master'].map(step => <span className="active" key={step}>{step}</span>)}</div><p className="footnote">* Corrective EQ only when needed. The waveform is illustrative; no audio is played.</p></div></Detail></div></section>
    <section className="section grammar-section"><div className="wrap"><Reveal><SectionHeading number="04" label="OUR VISUAL VOICE" title={<>We have already shown<br /><span className="muted">how we like to edit.</span></>}>Around 172 published videos are examples of our visual language. They can become a BRUKXT Editing Grammar.</SectionHeading></Reveal><div className="grammar"><div className="grammar-number"><span>≈</span>172<small>VIDEOS ALREADY CONTAIN PATTERNS</small></div><div className="grammar-analysis"><h3>Find patterns, then learn from human decisions.</h3><p>Shot duration, cut frequency, beats and phrases, build and drop behavior, DJ/crowd/wide balance, movement, composition, and energy before a cut. Where RAW cameras remain, compare every view with the final human edit.</p><div className="edit-strip"><span>DJ</span><span>WIDE</span><span>CROWD</span><span>DJ</span><span>CROWD</span></div><Waveform seed={6} /></div></div><p className="principle-line">Infrastructure first. Analysis second. Learning third.</p></div></section>
    <section className="section light-section"><div className="wrap"><Reveal><SectionHeading number="05" label="START SMALL" title={<>Two cameras.<br /><span className="muted">One real proof.</span></>}>The first prototype needs no machine learning. It needs reliable recording, fault detection, and a human who can take over.</SectionHeading></Reveal><div className="roadmap"><div className="split-heading"><h3>Every level<br />already helps.</h3><p>Most individual tools already exist. Our engineering task is to connect them into a dependable system.</p></div><div className="roadmap-tabs" role="group" aria-label="Development levels">{levels.map(([name], index) => <button key={name} onClick={() => setLevel(index)} aria-pressed={index === level}><span>LEVEL 0{index + 1}</span><strong>{name}</strong><small>{index === 0 ? 'START HERE' : 'NEXT LAYER'}</small></button>)}</div><div className="roadmap-detail"><span className="large-index">0{level + 1}</span><div><h3>{levels[level][1]}</h3><p>{levels[level][3]}</p><span className="micro">{levels[level][2]}</span></div></div></div></div></section>
    <section className="closing dark-section"><div className="wrap"><Reveal><span className="eyebrow">THIS IS THE POINT</span><h2>The artist ends the set.</h2></Reveal><Reveal className="closing-next"><h2>The system already knows<br /><span className="muted">what comes next.</span></h2></Reveal><div className="closing-chain">{['Recording', 'Audio', 'Sync', 'Edit', 'QC', 'Upload', 'Artist notified', 'Archive'].map((text, index) => <span key={text}><small>0{index + 1}</small>{text}<b>✓</b></span>)}</div><div className="closing-bottom"><p>Stop watching the pipeline.<br /><span className="muted">Start improving it.</span></p><a href="#main" className="inverse-button">Back to the top <span>↑</span></a></div><footer><span>ClubOS / Media</span><span>BRUKXT internal vision · interactive prototype</span><a href="#main">Top ↑</a></footer></div></section></main><SiteFooter locale="en" /></>;
}
