import Link from 'next/link';
import { PageIntro, SiteFooter, SiteHeader } from '../components/site-shell';

const branches = [
  ['01', 'Light', 'Світло як авторський інструмент.', 'Ксенія задає поведінку. Система перетворює музику на керуючі сигнали.', '/light', 'AUDIO → ARTISTIC LOGIC → LIGHT'],
  ['02', 'Media', 'Сет закінчився. Робота теж.', 'Запис, режисура, відновлення, монтаж і доставка — під людським наглядом.', '/media', 'CAPTURE → DIRECT → DELIVER'],
  ['03', 'Archive', 'Файли знаходять своє місце.', 'Спочатку індекс. Потім перевірка. Подія, артист і матеріали знову пов’язані.', '/files', 'INDEX → VERIFY → ORGANIZE'],
  ['04', 'People', 'Кожному — свою картину.', 'Творчий простір, пульс активних справ і зрозумілий план закупівель.', '/team', 'CONTEXT → DECISION → PARTICIPATION'],
];
export default function Home() {
  return <><SiteHeader /><main><PageIntro label="BRUKXT / СПІЛЬНА ВІЗІЯ" title={<>Важлива робота.<br /><span className="muted">Спільна система.</span></>} text="Робити те, що має значення. Бачити, де потрібна участь. Створювати власні інструменти разом — замість тримати весь клуб у чиїйсь голові." />
    <section className="wrap home-system"><div className="home-system-top"><span className="micro">ОДИН КОНТЕКСТ / РІЗНІ НАПРЯМИ</span><span className="micro">ВНУТРІШНІЙ ПРОТОТИП</span></div><div className="core-orbit"><span>Люди</span><span>Події</span><strong>ClubOS</strong><span>Домовленості</span><span>Стан</span></div><div className="branch-lines" aria-hidden="true"><i /><i /><i /><i /></div><div className="home-branch-labels"><Link href="/light">Light <span>↗</span></Link><Link href="/media">Media <span>↗</span></Link><Link href="/files">Archive <span>↗</span></Link><Link href="/team">People <span>↗</span></Link></div><p>Модулі обмінюються подіями. Команда бачить спільну картину.</p></section>
    <section className="section wrap"><div className="split-heading"><h2 className="hub-h2">Менше наздоганяти.<br /><span className="muted">Більше впливати.</span></h2><p>Система збирає контекст, готує наступний крок і показує винятки. Людина визначає напрям, приймає важливі рішення й долучається там, де хоче або де потрібна.</p></div><div className="hub-principles"><div><span>01 / ПАМ’ЯТЬ</span><h3>Не шукати по чатах.</h3><p>Домовленість має джерело, час, відповідального та зв’язок із конкретною справою.</p></div><div><span>02 / ПЕРЕДБАЧУВАНІСТЬ</span><h3>Бачити раніше.</h3><p>Оновлений прайс, нестача готівки, зміна таймінгу чи зникла камера — привід діяти до того, як це стане сюрпризом.</p></div><div><span>03 / УЧАСТЬ</span><h3>Залишатися автором.</h3><p>Автоматика бере рутину. Команда зберігає контроль і сама формує інструменти, якими користується.</p></div></div></section>
    <section className="section light-section"><div className="wrap"><div className="split-heading"><h2 className="hub-h2">Чотири входи.<br /><span className="muted">Одна система.</span></h2><p>Кожен напрям можна дослідити окремо. Усі — частини однієї розмови про те, як ми хочемо працювати.</p></div><div className="branch-cards">{branches.map(([num, name, title, desc, href, chain]) => <Link className="branch-card" href={href} key={name}><div className="branch-card-top"><span>{num} / {name}</span><b>↗</b></div><h3>{title}</h3><p>{desc}</p><span className="micro">{chain}</span></Link>)}</div></div></section>
    <section className="hub-closing dark-section"><div className="wrap"><span className="eyebrow">НАВІЩО МИ ЦЕ БУДУЄМО</span><h2>Важливі задачі.<br /><span className="muted">А не ті, які більше нікому зробити.</span></h2><p>Нагляд. Участь за потреби й за бажанням. Більше простору для своєї справи.</p></div></section>
  </main><SiteFooter /></>;
}
