'use client';

import { useState } from 'react';
import { Segmented } from './ui';
const tasks = [
  { name: 'Світло', title: 'Один художній пресет.', outcome: 'Ксенія порівнює нову поведінку з поточною й може пояснити, який варіант відповідає задуму.', prompt: 'Прочитай README.md і CONTRIBUTING.md. Працюємо над /light у components/light-playground.tsx. Допоможи додати один пресет «Напруга»: світло відкривається поступово, слабкий сигнал ігнорується. Спочатку поясни простими словами, які параметри треба змінити. Покажи маленьку зміну, збережи ручний blackout і reduced-motion. Разом перевіримо відчуття в браузері. Після цього опиши пресет у документації.' },
  { name: 'Пульс', title: 'Один корисний сигнал.', outcome: 'Микола бачить важливу зміну, її джерело та причину, чому саме зараз потрібна увага.', prompt: 'Прочитай README.md і CONTRIBUTING.md. Працюємо над простором Миколи в components/team-workspace.tsx. Допоможи додати один демосигнал: термін важливої домовленості змінився. Покажи джерело, старий і новий час, рівень впевненості та наступне рішення. Пояснюй зміни коротко. Перевіримо фільтри й те, що «ознайомився» не означає «виконано». Використовуй лише вигадані дані.' },
  { name: 'Бар', title: 'Одна зрозуміла закупівля.', outcome: 'Барменеджер звіряє один рядок вручну й бачить, як ціна впливає на необхідну суму.', prompt: 'Прочитай README.md і CONTRIBUTING.md. Працюємо над lib/bar.ts і барним простором у components/team-workspace.tsx. Допоможи додати один демонстраційний товар з одиницею виміру, залишком, цільовим запасом, старою й новою ціною. Поясни розрахунок кількості та суми на одному прикладі. Перевір випадки: товару вже достатньо; каси вистачає; готівка нижче резерву. Після зміни перевіримо npm test.' },
  { name: 'Архів', title: 'Один відновлений зв’язок.', outcome: 'Команда підтверджує, до якої події належить приклад, а невідоме залишається на розгляд.', prompt: 'Прочитай README.md і CONTRIBUTING.md. Працюємо над Archive у components/pipeline.tsx. Допоможи показати один демоприклад невпевненої прив’язки файлу до події: джерело припущення, альтернативу й кнопку ручного підтвердження. Дані лише вигадані. Пройдемо Index → Verify → Reorganize і перевіримо, що непідтверджений матеріал не зникає.' },
];
export function FirstTask() {
  const [choice, setChoice] = useState(0);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState(false);
  return <div className="first-task"><Segmented label="Перший напрям розробки" options={tasks.map(t => t.name)} value={choice} onChange={n => { setChoice(n); setCopied(false); setError(false); }} /><div className="first-task-body"><div><span className="eyebrow">ОДНА ЗАДАЧА / ОДИН ВИДИМИЙ РЕЗУЛЬТАТ</span><h3>{tasks[choice].title}</h3><p>{tasks[choice].outcome}</p><button className="primary-button" onClick={async () => { try { await navigator.clipboard.writeText(tasks[choice].prompt); setCopied(true); setError(false); } catch { setError(true); } }}>{copied ? '✓ Завдання скопійовано' : 'Скопіювати завдання для агента'}</button><span className="footnote" role="status">{error ? 'Копіювання недоступне. Текст можна виділити у полі поруч.' : copied ? 'Вставте у свого coding-агента, відкривши цей репозиторій.' : 'Текст можна адаптувати під свій задум.'}</span></div><textarea aria-label="Стартове завдання для coding-агента" readOnly value={tasks[choice].prompt} /></div></div>;
}
