'use client';

import { useState } from 'react';
import { Segmented } from './ui';
const tasks = [
  { name: 'Світло', title: 'Один художній пресет.', outcome: 'Ксенія порівнює нову поведінку з поточною й може пояснити, який варіант відповідає задуму.', prompt: 'Прочитай README.md і CONTRIBUTING.md. Працюємо над /light у components/light-playground.tsx. Допоможи додати один пресет «Напруга»: світло відкривається поступово, слабкий сигнал ігнорується. Спочатку поясни простими словами, які параметри треба змінити. Покажи маленьку зміну, збережи ручний blackout і reduced-motion. Разом перевіримо відчуття в браузері. Після цього опиши пресет у документації.' },
  { name: 'Пульс', title: 'Один корисний сигнал.', outcome: 'Микола бачить важливу зміну, її джерело та причину, чому саме зараз потрібна увага.', prompt: 'Прочитай README.md і CONTRIBUTING.md. Працюємо над простором Миколи в components/team-workspace.tsx. Допоможи додати один демосигнал: термін важливої домовленості змінився. Покажи джерело, старий і новий час, рівень впевненості та наступне рішення. Пояснюй зміни коротко. Перевіримо фільтри й те, що «ознайомився» не означає «виконано». Використовуй лише вигадані дані.' },
  { name: 'Бар', title: 'Одна зрозуміла закупівля.', outcome: 'Барменеджер звіряє один рядок вручну й бачить, як ціна впливає на необхідну суму.', prompt: 'Прочитай README.md і CONTRIBUTING.md. Працюємо над lib/bar.ts і барним простором у components/team-workspace.tsx. Допоможи додати один демонстраційний товар з одиницею виміру, залишком, цільовим запасом, старою й новою ціною. Поясни розрахунок кількості та суми на одному прикладі. Перевір випадки: товару вже достатньо; каси вистачає; готівка нижче резерву. Після зміни перевіримо npm test.' },
  { name: 'Архів', title: 'Один відновлений зв’язок.', outcome: 'Команда підтверджує, до якої події належить приклад, а невідоме залишається на розгляд.', prompt: 'Прочитай README.md і CONTRIBUTING.md. Працюємо над Archive у components/pipeline.tsx. Допоможи показати один демоприклад невпевненої прив’язки файлу до події: джерело припущення, альтернативу й кнопку ручного підтвердження. Дані лише вигадані. Пройдемо Index → Verify → Reorganize і перевіримо, що непідтверджений матеріал не зникає.' },
];
const tasksEn = [
  { name: 'Light', title: 'One artistic preset.', outcome: 'Kseniia compares the new behavior with the current one and can explain which matches her intention.', prompt: 'Read README.md and CONTRIBUTING.md. We are working on /light in components/light-playground.tsx. Help add one preset called “Tension”: light opens gradually and ignores weak signals. First explain in plain language which parameters need to change. Make a small change, preserve manual blackout and reduced motion. Then we will review the feeling in the browser. Document the preset afterward.' },
  { name: 'Pulse', title: 'One useful signal.', outcome: 'Mykola sees an important change, its source, and why it needs attention now.', prompt: 'Read README.md and CONTRIBUTING.md. We are working on Mykola’s space in components/team-workspace.tsx. Add one sample signal: the deadline for an important agreement has changed. Show the source, old and new times, confidence, and next decision. Explain changes briefly. Check the filters and make sure “seen” does not mean “done”. Use fictional data only.' },
  { name: 'Bar', title: 'One clear purchase.', outcome: 'The bar manager verifies one row manually and sees how the price affects the required amount.', prompt: 'Read README.md and CONTRIBUTING.md. We are working on lib/bar.ts and the bar space in components/team-workspace.tsx. Add one sample product with a unit, current stock, target stock, old and new price. Explain the quantity and amount on one example. Check the cases where stock is sufficient, cash is sufficient, and cash is below reserve. Then run npm test.' },
  { name: 'Archive', title: 'One restored connection.', outcome: 'The team confirms which event an example belongs to, while unknown items stay in review.', prompt: 'Read README.md and CONTRIBUTING.md. We are working on Archive in components/pipeline.tsx. Show one sample uncertain match between a file and an event, including the source of the suggestion, an alternative, and a manual confirmation button. Use fictional data only. Walk through Index → Verify → Reorganize and check that unconfirmed material does not disappear.' },
];
export function FirstTask({ locale = 'uk' }: { locale?: 'uk' | 'en' }) {
  const en = locale === 'en';
  const choices = en ? tasksEn : tasks;
  const [choice, setChoice] = useState(0);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState(false);
  return <div className="first-task"><Segmented label={en ? 'First development area' : 'Перший напрям розробки'} options={choices.map(t => t.name)} value={choice} onChange={n => { setChoice(n); setCopied(false); setError(false); }} /><div className="first-task-body"><div><span className="eyebrow">{en ? 'ONE TASK / ONE VISIBLE RESULT' : 'ОДНА ЗАДАЧА / ОДИН ВИДИМИЙ РЕЗУЛЬТАТ'}</span><h3>{choices[choice].title}</h3><p>{choices[choice].outcome}</p><button className="primary-button" onClick={async () => { try { await navigator.clipboard.writeText(choices[choice].prompt); setCopied(true); setError(false); } catch { setError(true); } }}>{copied ? (en ? '✓ Task copied' : '✓ Завдання скопійовано') : (en ? 'Copy task for the agent' : 'Скопіювати завдання для агента')}</button><span className="footnote" role="status">{error ? (en ? 'Copying is unavailable. Select the text in the field beside it.' : 'Копіювання недоступне. Текст можна виділити у полі поруч.') : copied ? (en ? 'Paste it into your coding agent with this repository open.' : 'Вставте у свого coding-агента, відкривши цей репозиторій.') : (en ? 'Adapt the text to your idea.' : 'Текст можна адаптувати під свій задум.')}</span></div><textarea aria-label={en ? 'Starter task for a coding agent' : 'Стартове завдання для coding-агента'} readOnly value={choices[choice].prompt} /></div></div>;
}



