import Link from 'next/link';
import { PageIntro, SiteFooter, SiteHeader } from '../../components/site-shell';

export const metadata = { title: 'ClubOS — Meaningful work. One shared system.', description: 'A shared BRUKXT vision for operations, reactive light, media, and the archive.' };
const branches = [
  ['01', 'Light', 'Light as a creative instrument.', 'Kseniia shapes its behavior. The system turns music into control signals.', '/en/light', 'AUDIO → ARTISTIC LOGIC → LIGHT'],
  ['02', 'Media', 'The set ends. So does the busywork.', 'Recording, directing, recovery, editing, and delivery under human supervision.', '/en/media', 'CAPTURE → DIRECT → DELIVER'],
  ['03', 'Archive', 'Files find their place.', 'Index first, then verify. Events, artists, and media reconnect.', '/en/files', 'INDEX → VERIFY → ORGANIZE'],
  ['04', 'People', 'A view for every role.', 'Creative space, a pulse of active work, and a clear purchasing plan.', '/en/team', 'CONTEXT → DECISION → PARTICIPATION'],
];
export default function EnglishHome() {
  return <><SiteHeader locale="en" /><main><PageIntro label="BRUKXT / SHARED VISION" title={<>Meaningful work.<br /><span className="muted">One shared system.</span></>} text="Do what matters. See where you can contribute. Build our own tools together, so the whole club does not have to live in someone's head." />
    <section className="wrap home-system"><div className="home-system-top"><span className="micro">ONE CONTEXT / MANY DIRECTIONS</span><span className="micro">INTERNAL PROTOTYPE</span></div><div className="core-orbit"><span>People</span><span>Events</span><strong>ClubOS</strong><span>Agreements</span><span>Status</span></div><div className="branch-lines" aria-hidden="true"><i /><i /><i /><i /></div><div className="home-branch-labels"><Link href="/en/light">Light <span>↗</span></Link><Link href="/en/media">Media <span>↗</span></Link><Link href="/en/files">Archive <span>↗</span></Link><Link href="/en/team">People <span>↗</span></Link></div><p>Modules share events. The team sees the same picture.</p></section>
    <section className="section wrap"><div className="split-heading"><h2 className="hub-h2">Less catching up.<br /><span className="muted">More influence.</span></h2><p>The system gathers context, prepares the next step, and surfaces exceptions. People set direction, make important decisions, and join in where they want or are needed.</p></div><div className="hub-principles"><div><span>01 / MEMORY</span><h3>Stop searching through chats.</h3><p>Every agreement has a source, a time, an owner, and a link to the work it concerns.</p></div><div><span>02 / FORESIGHT</span><h3>See it sooner.</h3><p>A new price list, a cash shortfall, a schedule change, or a missing camera calls for action before it becomes a surprise.</p></div><div><span>03 / PARTICIPATION</span><h3>Stay the author.</h3><p>Automation handles routine work. The team keeps control and shapes the tools it uses.</p></div></div></section>
    <section className="section light-section"><div className="wrap"><div className="split-heading"><h2 className="hub-h2">Four entry points.<br /><span className="muted">One system.</span></h2><p>Explore each direction on its own. All four are part of one conversation about how we want to work.</p></div><div className="branch-cards">{branches.map(([num, name, title, desc, href, chain]) => <Link className="branch-card" href={href} key={name}><div className="branch-card-top"><span>{num} / {name}</span><b>↗</b></div><h3>{title}</h3><p>{desc}</p><span className="micro">{chain}</span></Link>)}</div></div></section>
    <section className="hub-closing dark-section"><div className="wrap"><span className="eyebrow">WHY WE ARE BUILDING THIS</span><h2>Work that matters.<br /><span className="muted">Not the work nobody else can pick up.</span></h2><p>Oversight. Participation when needed or wanted. More room for your own work.</p></div></section>
  </main><SiteFooter locale="en" /></>;
}
