import type { Metadata } from 'next';
import { SiteFooter, SiteHeader } from '../../../components/site-shell';
import '../../start/setup.css';

export const metadata: Metadata = { title: 'Set up your first coding agent', description: 'Install Claude Code or Codex on Windows or macOS, then make a first file.' };

const routes = [
  { title: 'Claude Code / macOS', command: 'curl -fsSL https://claude.ai/install.sh | bash', verify: 'claude --version', source: 'https://code.claude.com/docs/en/setup' },
  { title: 'Claude Code / Windows PowerShell', command: 'irm https://claude.ai/install.ps1 | iex', verify: 'claude --version', source: 'https://code.claude.com/docs/en/setup' },
  { title: 'Codex CLI / macOS', command: 'curl -fsSL https://chatgpt.com/codex/install.sh | sh', verify: 'codex --version', source: 'https://learn.chatgpt.com/docs/codex/cli' },
  { title: 'Codex CLI / Windows PowerShell', command: 'irm https://chatgpt.com/codex/install.ps1 | iex', verify: 'codex --version', source: 'https://learn.chatgpt.com/docs/codex/cli' },
];

export default function EnglishStartPage() {
  return <><SiteHeader current="start" locale="en" /><main className="setup-page"><div className="setup-wrap"><div className="setup-intro"><div><span className="setup-eyebrow">CLUBOS / PRACTICE 01</span><h1>Start your first<br /><span>coding agent.</span></h1><p>From an empty terminal to a page you can open.<br />One step, one action, one visible result.</p></div><div className="setup-intro-note"><span>FOR THE FIRST SESSION</span><strong>Start on your own computer.</strong><p>You need an internet connection and an account with access to the tool. No coding knowledge is required.</p></div></div><section className="setup-card"><div className="setup-card-meta"><span>CHOOSE ONE ROUTE</span><span>WINDOWS / macOS</span></div><h2>Install and verify your tool.</h2><p className="setup-why">Open Terminal on macOS or PowerShell on Windows, choose exactly one route below, then paste its install command. Close and reopen the terminal before verifying the version.</p><div className="setup-missing">{routes.map(route => <article className="setup-expected" key={route.title}><span>→</span><div><strong>{route.title}</strong><pre className="setup-en-command">{route.command}</pre><p>Verify: <code>{route.verify}</code></p><a className="setup-source-link" href={route.source} target="_blank" rel="noreferrer">Official installation instructions ↗</a></div></article>)}</div><div className="setup-next-lesson"><span className="setup-eyebrow">FIRST SESSION</span><h3>Open a folder, sign in, and ask for one small result.</h3><p>Run <code>claude</code> or <code>codex</code> from an empty practice folder, complete sign-in in your browser, then paste the prompt below.</p><pre className="setup-en-command">Create hello.html in the current folder. Make a Ukrainian greeting and a card for a fictional club event with a title, date, and description. Put all HTML and CSS in one file, use no libraries or external resources, and do not change other files. Explain where the file is saved and how to open it in a browser.</pre><p>Open <code>hello.html</code> in a browser, take a screenshot, and share it with the team. If you get stuck, include your operating system, tool name, the step you reached, what you expected, and the exact error—without passwords, keys, or sign-in codes.</p></div></section></div></main><SiteFooter locale="en" /></>;
}
