'use client';

import { useEffect, useState } from 'react';
import { SiteHeader } from '../../components/site-shell';
import { ControlRoom, Preflight } from '../../components/control-room';
import { AfterSet, Archive, AudioPipeline, Crew, Fallback, MediaTimeline, Pipeline } from '../../components/pipeline';
import { DemoLabel, Detail, Reveal, SectionHeading, Segmented, Waveform } from '../../components/ui';

const manualTasks = ['Підготувати камери', 'Capture cards', 'Налаштувати OBS', 'Перевірити сигнал', 'Почати запис', 'Записати аудіо', 'Дивитися в OBS', 'Помітити чорний кадр', 'Помітити зависання', 'Перемкнути камеру', 'Пам’ятати таймінг', 'Зупинити запис', 'Знайти файли', 'Чий це сет?', 'Синхронізувати камери', 'Синхронізувати master', 'Нарізати сети', 'Обробити аудіо', 'Рендер', 'Перевірити рендер', 'Завантажити', 'Знайти контакт', 'Надіслати', 'Хто ще чекає?', 'Навести лад', 'Знайти старий проєкт'];
const levels = [
  ['Reliable', 'Спочатку — надійність.', 'Recording automation · health checks · fallbacks · OBS control · manual override · event logging', 'Запис іде. Збій помічено. Керування залишається у людини.'],
  ['Aware', 'Система розуміє контекст.', 'Audio analysis · camera analysis · artist timeline · automatic synchronization · archive integration', 'Сигнали, артисти й файли належать одній події та часовій шкалі.'],
  ['Director', 'З’являється режисура.', 'Rule-based directing · music-aware cuts · camera quality scoring', 'Монтажні правила й музичні переходи визначають наступний кадр.'],
  ['BRUKXT style', 'Потім — наш почерк.', 'Historical edit analysis · BRUKXT Editing Grammar · supervised dataset · learned Director', 'Навчання спирається на перевірені дані та вже надійну інфраструктуру.'],
  ['Pipeline', 'Весь шлях до артиста.', 'Automatic post-production · audio mastering · QC · upload · artist delivery · archive', 'Сет не закінчується чергою ручних нагадувань.'],
];

function SignalDiagram() {
  return <div className="signal-diagram" aria-label="Камери, аудіо й таймлайн об’єднуються в Media Engine та готовий сет"><div className="signal-inputs">{['CAM A', 'CAM B', 'CAM C', 'MASTER', 'TIMELINE'].map((n, i) => <div key={n}><span>{n}</span>{i < 4 ? <Waveform seed={i} /> : <div className="mini-timeline"><i /><i /><i /></div>}</div>)}</div><svg className="signal-wires" viewBox="0 0 230 240" preserveAspectRatio="none" aria-hidden="true">{[24, 72, 120, 168, 216].map((y, i) => <path key={y} pathLength="100" className={`wire wire-${i}`} d={`M 0 ${y} H 50 C 125 ${y} 100 120 180 120 H 230`} />)}</svg><div className="signal-engine"><span className="micro">CLUBOS / MEDIA</span><span className="engine-mark" aria-hidden="true"><i /><i /><i /></span><strong>Менше дій.<br />Більше контролю.</strong></div><div className="signal-output"><span className="output-line" /><div><span className="ready-dot">✓</span><strong>SET READY</strong><span className="micro">ARTIST → ARCHIVE</span></div></div></div>;
}

export default function Home() {
  const [workflow, setWorkflow] = useState(0);
  const [level, setLevel] = useState(0);
  const [grammar, setGrammar] = useState(0);
  const [active, setActive] = useState('vision');
  useEffect(() => {
    const observer = new IntersectionObserver(entries => {
      entries.forEach(entry => { if (entry.isIntersecting) setActive(entry.target.id); });
    }, { rootMargin: '-15% 0px -65% 0px' });
    document.querySelectorAll('section[data-nav]').forEach(el => observer.observe(el));
    return () => observer.disconnect();
  }, []);
  return <>
    <a className="skip-link" href="#main">До змісту</a>
    <SiteHeader current="media" />
    <main id="main">
      <section className="hero wrap" id="vision" data-nav>
        <div className="hero-meta"><span className="eyebrow">BRUKXT MEDIA ENGINE</span><span className="micro">ВІЗІЯ / ПРОТОТИП 01</span></div>
        <h1>Сет закінчився.<br /><span>Робота теж.</span></h1>
        <div className="hero-bottom"><p>Від першого кадру до готового запису в артиста.<br />Без людини, яка має пам’ятати про кожен крок.</p><a href="#burden" className="round-link"><span>Подивитися, як</span><b aria-hidden="true">↓</b></a></div>
        <SignalDiagram />
        <div className="hero-caption"><span>МАШИНИ КОНТРОЛЮЮТЬ МАШИНИ.<br className="mobile-only" /> ЛЮДИ КОНТРОЛЮЮТЬ СИСТЕМУ.</span><span>КОНЦЕПЦІЯ ВСЕРЕДИНІ CLUBOS</span></div>
      </section>

      <section className="section light-section" id="burden"><div className="wrap"><Reveal><SectionHeading number="01" label="ЗНАЙОМА СИТУАЦІЯ" title={<>Жодна дія не складна.<br /><span className="muted">Складно пам’ятати про всі.</span></>}>Роками ми не просто знімаємо сети. Ми супроводжуємо кожен файл від камери до повідомлення артисту.</SectionHeading></Reveal>
        <div className="workflow-switch"><span className="micro">ОДИН СЕТ. УВЕСЬ ШЛЯХ.</span><Segmented label="Ручний чи автоматизований процес" options={['Як зараз', 'Як може бути']} value={workflow} onChange={setWorkflow} /></div>
        <div className={`workflow ${workflow ? 'simplified' : ''}`}><div className="task-cloud" aria-hidden={workflow === 1}>{manualTasks.map((task, i) => <span key={task} style={{ '--order': i } as React.CSSProperties}>{task}<small>{String(i + 1).padStart(2, '0')}</small></span>)}</div><div className="simple-flow" aria-hidden={workflow === 0}><div><span className="micro">01 / ТРИГЕР</span><h3>Артист починає</h3><p>Таймлайн уже знає контекст.</p></div><span className="flow-arrow">→</span><div className="flow-engine"><span className="micro">02 / СИСТЕМА</span><h3>Media Engine</h3><p>Записує. Перевіряє. Готує.</p></div><span className="flow-arrow">→</span><div><span className="micro">03 / РЕЗУЛЬТАТ</span><h3>Артист отримує сет</h3><p>Архів оновлюється.</p></div></div></div>
        <div className="burden-consequences"><div><span>01</span><h3>Запис є.<br />Результату немає.</h3><p>Файли накопичуються. Монтаж стає чергою. Артисти чекають.</p></div><div><span>02</span><h3>Помилка сталася.<br />Ми ще не знаємо.</h3><p>Чорний кадр, зависла карта, відсутній master. Іноді це видно лише після сету.</p></div><div><span>03</span><h3>Все тримається<br />на чиїйсь пам’яті.</h3><p>Де файл? Хто ще чекає? Хто мав надіслати? Техніка забирає людську увагу.</p></div></div>
      </div></section>

      <section className="statement wrap"><Reveal><span className="eyebrow">ЩО МИ ХОЧЕМО ПОВЕРНУТИ</span><h2>Вашу увагу.</h2><p>Камерам. Простору. Музиці.<br /><span className="muted">Усьому, заради чого ми це робимо.</span></p></Reveal><div className="statement-note">Не замінити відеокоманду.<br />Зняти з неї постійний нагляд за машинами.</div></section>

      <section className="section control-section" id="control" data-nav><div className="wrap"><Reveal><SectionHeading number="02" label="СИСТЕМА ПРАЦЮЄ. ВИ КЕРУЄТЕ." title={<>Автоматика.<br /><span className="muted">З вашим останнім словом.</span></>}>Система готується, записує й стежить за сигналами. Ви задаєте правила, бачите причини рішень і можете втрутитися будь-якої миті.</SectionHeading></Reveal><Preflight /><div className="demo-intro"><h3>Спробуйте бути режисером.</h3><p>Оберіть камеру. Зафіксуйте кадр. А потім зламайте CAM B.</p></div><ControlRoom /><div className="console-footnote"><span>Усі сигнали, кадри й показники — симуляція.</span><span>Жодної реальної камери чи OBS не підключено.</span></div>
        <div className="subsection"><div className="split-heading"><h3>Збій має зменшувати можливості.<br /><span className="muted">А не забирати весь ефір.</span></h3><p>Коли один рівень недоступний, наступний бере роботу на себе. Жодна зовнішня AI-модель не є єдиною точкою відмови.</p></div><Fallback /></div>
        <Detail title="Як влаштована віртуальна технічна команда"><p className="detail-intro">Окремі ролі співпрацюють через стан і події. Це не один гігантський AI. Натисніть на роль, щоб побачити її відповідальність.</p><Crew /></Detail>
        <Detail title="Realtime: без великої LLM між камерою та OBS"><div className="architecture-inputs"><div><b>CAMERAS</b><span>Computer vision features</span></div><div><b>AUDIO</b><span>DSP features</span></div><div><b>SYSTEM</b><span>Telemetry</span></div></div><div className="architecture-flow"><span>State</span><b>→</b><span>Decision layer</span><b>→</b><span>Rules / invariants</span><b>→</b><strong>OBS control</strong></div><p>У realtime — недорогі локальні обчислення. Важкий AI аналізує асинхронно або offline. Недоступність зовнішнього сервісу не зупиняє локальний запис, правила й ручне керування.</p></Detail>
      </div></section>

      <section className="section dark-section" id="pipeline" data-nav><div className="wrap"><Reveal><SectionHeading number="03" label="НІЧОГО НЕ ПОТРІБНО ПАМ’ЯТАТИ" title={<>Один сет.<br /><span className="muted">Один безперервний шлях.</span></>}>ClubOS уже знає хто, де й коли грає. Media Engine знає, що робити із сигналами, файлами й готовим результатом.</SectionHeading></Reveal><Pipeline /><div className="after-heading"><span className="eyebrow">03:00:00 / ARTIST SET END</span><h2>Ви закриваєте ніч.<br /><span className="muted">Система закриває роботу.</span></h2></div><AfterSet /><div className="no-queue"><span>↗</span><p>Жодної забутої черги артистів.</p></div><Detail title="Синхронізація: всі джерела на одній шкалі"><MediaTimeline /></Detail><Detail title="Аудіо: джерело незмінне, master відтворюваний"><AudioPipeline /></Detail></div></section>

      <section className="section grammar-section"><div className="wrap"><Reveal><SectionHeading number="04" label="НАШ ВІЗУАЛЬНИЙ ПОЧЕРК" title={<>Ми вже показали,<br /><span className="muted">як любимо монтувати.</span></>}>Приблизно 172 опубліковані відео — це приклади нашої візуальної мови. Їх можна перетворити на BRUKXT Editing Grammar.</SectionHeading></Reveal><div className="grammar"><div className="grammar-number"><span>≈</span>172<small>ВІДЕО ВЖЕ МІСТЯТЬ ПАТЕРНИ</small></div><div className="grammar-analysis"><Segmented label="Етап аналізу монтажу" options={['Зараз', 'Наступний крок']} value={grammar} onChange={setGrammar} /><h3>{grammar === 0 ? 'Побачити закономірності.' : 'Навчатися на людському рішенні.'}</h3><p>{grammar === 0 ? 'Тривалість кадру. Частота перемикань. Біти й музичні фрази. Поведінка на build та drop. Баланс DJ / crowd / wide, рух, композиція й енергія перед склейкою.' : 'Де збереглися RAW-камери, зіставляємо всі доступні ракурси з фінальним людським монтажем. Так з’являються приклади того, чому обрано саме цей кадр.'}</p><div className="edit-strip" aria-label="Схема тривалостей кадрів"><span>DJ</span><span>WIDE</span><span>CROWD</span><span>DJ</span><span>CROWD</span></div><Waveform seed={6} /><div className="grammar-chain">{(grammar === 0 ? ['Shot detection', 'Audio + visual analysis', 'Edit timing', 'Patterns', 'Editing Grammar'] : ['RAW cameras', '+ Human edit', 'Supervised dataset', 'BRUKXT Director model']).map(t => <span key={t}>{t}</span>)}</div></div></div><p className="principle-line">Спочатку інфраструктура. Потім аналіз. Потім навчання.</p><p className="footnote">172 — орієнтовна кількість із внутрішнього брифу. Модель ще не навчена. Патерни — основа для дослідження, а не гарантія художнього рішення.</p></div></section>

      <section className="section light-section" id="archive"><div className="wrap"><Reveal><SectionHeading number="05" label="ПАМ’ЯТЬ ЗАМІСТЬ ХАОСУ" title={<>Старі папки.<br /><span className="muted">Нові зв’язки.</span></>}>Garbage Genie спершу розбирається, де що лежить. Відновлює зв’язок «подія → артист → медіа». І лише після перевірки пропонує порядок.</SectionHeading></Reveal><Archive /></div></section>

      <section className="section wrap human-section"><Reveal><SectionHeading number="06" label="НОВА ЛЮДСЬКА РОБОТА" title={<>Менше обслуговування.<br /><span className="muted">Більше авторства.</span></>} /></Reveal><div className="before-after"><div className="before"><span className="eyebrow">ДО / ТРИМАТИ ВСЕ В ГОЛОВІ</span>{['Дивитися в OBS і перевіряти камери', 'Вчасно починати й зупиняти записи', 'Копіювати, перейменовувати, шукати', 'Синхронізувати й робити базовий монтаж', 'Обробляти аудіо та завантажувати', 'Пам’ятати, кому ще не надіслали'].map(t => <p key={t}><span>−</span>{t}</p>)}</div><div className="after"><span className="eyebrow">ПІСЛЯ / ПРИЙМАТИ ВАЖЛИВІ РІШЕННЯ</span>{['Ставити камери й обирати оптику', 'Вирішувати фізичні проблеми на місці', 'Визначати візуальну мову BRUKXT', 'Переглядати важливі монтажі', 'Приймати творчі рішення', 'Покращувати систему й долати винятки'].map(t => <p key={t}><span>↗</span>{t}</p>)}</div></div><p className="principle-line">Не менше людей. Менше уваги на передбачувану роботу машин.</p></section>

      <section className="section light-section" id="build" data-nav><div className="wrap"><Reveal><SectionHeading number="07" label="ПОЧАТИ МОЖНА З МАЛОГО" title={<>Дві камери.<br /><span className="muted">Один реальний доказ.</span></>}>Першому прототипу не потрібне машинне навчання. Йому потрібно надійно записувати, помічати збій і дозволяти людині втрутитися.</SectionHeading></Reveal><div className="test-bench"><div className="bench-hardware"><span className="micro">TEST BENCH / HARDWARE</span><div className="bench-drawing" aria-hidden="true"><div className="draw-cameras"><span>CAM 01</span><span>CAM 02</span></div><div className="draw-capture"><i />2 × HDMI → USB<i /></div><div className="draw-laptop"><span>OBS</span><small>MEDIA ENGINE</small></div><div className="draw-audio">MASTER AUDIO →</div></div><p>2 камери · 2 карти захоплення<br />1 ноутбук · OBS · master audio</p></div><div className="bench-checklist"><span className="micro">MVP / КРИТЕРІЇ ГОТОВНОСТІ</span>{['Побачити обидві камери', 'Моніторити стан сигналу', 'Почати / зупинити OBS-запис', 'Почати / зупинити RAW-запис', 'Автоматично перемикати сцени', 'Помітити чорний або завмерлий кадр', 'Вилучити несправне джерело', 'Безпечно перейти на резерв', 'Спробувати відновлення', 'Записати причину кожного рішення', 'Негайно віддати контроль людині', 'Покликати її, коли це необхідно'].map((t, i) => <div key={t}><span>{String(i + 1).padStart(2, '0')}</span>{t}</div>)}</div></div><div className="bench-software"><span>SOFTWARE</span><p>Media Engine · OBS connector · camera health analysis · Director · Evaluator · Recovery Handler · event log · human control panel</p></div><div className="roadmap"><div className="split-heading"><h3>Кожен рівень<br />вже має користь.</h3><p>Більшість окремих інструментів уже існує. Наша інженерна задача — об’єднати їх у надійну систему.</p></div><div className="roadmap-tabs" role="group" aria-label="Рівні розвитку">{levels.map(([name], i) => <button key={name} onClick={() => setLevel(i)} aria-pressed={i === level}><span>LEVEL 0{i + 1}</span><strong>{name}</strong><small>{i === 0 ? 'ПОЧИНАЄМО ТУТ' : 'НАСТУПНИЙ ШАР'}</small></button>)}</div><div className="roadmap-detail"><span className="large-index">0{level + 1}</span><div><h3>{levels[level][1]}</h3><p>{levels[level][3]}</p><span className="micro">{levels[level][2]}</span></div></div></div></div></section>

      <section className="section wrap clubos-section"><Reveal><SectionHeading number="08" label="ЧАСТИНА CLUBOS" title={<>Контекст уже спільний.<br /><span className="muted">Можливостей стає більше.</span></>}>Media Engine — модуль у спільній архітектурі. Події, артисти й таймлайн не потрібно створювати ще раз у черговій окремій системі.</SectionHeading></Reveal><div className="module-map"><div><span className="eyebrow">CLUBOS / CORE CONCEPTS</span><div className="concepts">{['Event', 'Artist', 'Timeline', 'People', 'Tasks', 'Documents', 'System state'].map(t => <span key={t}>{t}</span>)}</div></div><div className="module-bridge"><span>↓ SUBSCRIBE</span><span>↑ PUBLISH</span></div><div><span className="eyebrow">MEDIA / NEW CAPABILITIES</span><div className="concepts">{['Cameras', 'Recordings', 'Streams', 'Media', 'Archive', 'Delivery'].map(t => <span key={t}>{t}</span>)}</div></div></div><div className="event-contract"><code>artist.set.ended</code><span>→ Media Engine →</span><code>media.delivery.ready</code></div><p className="footnote">Ілюстративні назви подій. Модуль підписується на факти, відкриває capabilities і публікує власний стан. Інші модулі можуть реагувати. Це напрям розвитку, не твердження про готову інтеграцію.</p></section>

      <section className="closing dark-section"><div className="wrap"><Reveal><span className="eyebrow">ОСЬ ЗАРАДИ ЧОГО</span><h2>Артист закінчує сет.</h2></Reveal><Reveal className="closing-next"><h2>Система вже знає,<br /><span className="muted">що відбувається далі.</span></h2></Reveal><div className="closing-chain">{['Recording', 'Audio', 'Sync', 'Edit', 'QC', 'Upload', 'Artist notified', 'Archive'].map((t, i) => <span key={t}><small>0{i + 1}</small>{t}<b>✓</b></span>)}</div><div className="closing-bottom"><p>Перестаємо наглядати за пайплайном.<br /><span className="muted">Починаємо його покращувати.</span></p><a href="#control" className="inverse-button">Спробувати ще раз <span>↑</span></a></div><footer><span>ClubOS / Media</span><span>Внутрішня візія BRUKXT · інтерактивний прототип</span><a href="#vision">На початок ↑</a></footer></div></section>
    </main>
  </>;
}
